language: node_js

node_js:
  - 9
  - 8

services:
- mysql

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

before_install:
  - mysql -e 'CREATE DATABASE innov8;'

install:
  - npm install

script:
  - npm run migrate
  - npm run test
  - npm run coverage
  - npm run build

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules